Made functions for serdes of a Msg
AlbertaSat/ex3_obc_fsw pull request #13
Opened 2024-06-13 22:15 UTC by rrasmuss4200

# Description
Made public functions for serializing and deserializing a Msg struct so they can be used anywhere

2024-06-14 20:08 UTC, dheadrick1618 commented on libs/message_structure/src/lib.rs
> +    let deserialized_msg: Msg = serde_json::from_reader(&mut cursor).unwrap();
Need to return a error type if this fails. Right now if this unwrap fails it will panic and crash the program, if you use a ' ? ' operator then it will propogate the error up to the calling function (return the err type) rather than crash the program.

2024-06-14 20:09 UTC, dheadrick1618 commented on libs/message_structure/src/lib.rs
> +    let _serialized_msg = serde_json::to_writer(&mut buf, &msg).unwrap();
Also use a ' ? ' here

2024-06-14 20:10 UTC, dheadrick1618 requested changes
Should propagate errors upward with '?' within functions that return a result rather than use unwraps and panic.

2024-06-14 22:16 UTC, rrasmuss4200 commented on libs/message_structure/src/lib.rs
> +    let _serialized_msg = serde_json::to_writer(&mut buf, &msg).unwrap();
Yes I agree. Should be good to go

2024-06-17 17:27 UTC, dheadrick1618 approved these changes
LGTM

2024-06-17 17:30 UTC, merged